name: Thomas Gfeller
favicon: null
layout_spectrum: 0.2411
typography_spectrum: 0.3622153657488525
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9c4c0'
    - '#9c9c9c'
    - '#121d19'
    - '#3e3b45'
    - '#9a3b19'
  brandStrength: 0.7853316531982273
  lightness: 0.3282015761360526
  saturation: 0.4412227049469948
  rhythmicContrast: 0.2832181628327817
purpose: []
